[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.3.0"  # Matches v0.32.1; install via `solana-install init 2.3.0`
[features]
resolution = true
skip-lint = false

[programs.localnet]
trading_competition = "HjmkkHv5A1SPbL4zjpRJjYVj33YTTq9QYyCPkx6x6HnB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
